### ISSUE TITLE
org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Pipe broken

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/quarkus-lsp4e#1]
Open application.properties. Wait around 5 seconds. After that you will see error log:

```
Sep 07, 2019 1:11:08 PM org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor run
SEVERE: java.io.IOException: Pipe broken
org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Pipe broken
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:120)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Pipe broken
	at com.redhat.quarkus.lsp4e.MyPipedInputStream.read(MyPipedInputStream.java:324)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:79)
	... 6 more

```

**Comment by angelozerr** [comment]
The problem comes from multi threading use with PipedInputStream. I have copied/pasted PipedInputStream/PipedOutputStream to MyPipedInputStream/MyPipedOutputStream and comment the call of Thread.currentThread() (see commit https://github.com/angelozerr/quarkus-lsp4e/commit/b863da4722b3f34aa24a4abd8275ec5ba9ca9ead) and problem is gone.

But is it a very good fix?

@fbricon @mickaelistria any help are welcome!

**Comment by mickaelistria** [comment]
> But is it a very good fix?

I'm afraid not. Streams producers/consumers here have to be single threaded as the order in which input (characters) are processed matters. We shouldn't remove things that ensures this invariant remains active.
Also, forking language standard APIs is not something we want to rely on: many improvements happen on those APIs version after version, and forking them make us unable to easily take advantage of those improvements.

I don't know yet what causes this issue, but I guess it's more in LSP4E orchestration of some operations. The fix should most likely be on that layer than on the stream one.

**Comment by angelozerr** [comment]
I agree with you @mickaelistria . My fix is very ugly -(

When this Quarkus LS integration will be the priority I hope we could work together with you, @fbricon and @jeffmaury

**Comment by angelozerr** [comment]
I think LSP4E should provide the capability to start a language server in the same JVM than Eclipse IDE. I had created this issue long time at https://bugs.eclipse.org/bugs/show_bug.cgi?id=533584 For th emoment thi sLocalStreamConnectionProvider  is hosted in this quarkus-lsp4e github project

**Comment by angelozerr** [comment]
I close this issue since now Quarkus LS starts with standard LSP4E process.

**Comment by mickaelistria** [comment]
Great!

**Comment by angelozerr** [comment]
See:

 * my server (process which starts the Quarkus LS with provcess) : https://github.com/angelozerr/quarkus-lsp4e/blob/master/com.redhat.quarkus.lsp4e/src/com/redhat/quarkus/lsp4e/QuarkusLanguageServer.java#L19
 * my client : https://github.com/angelozerr/quarkus-lsp4e/blob/master/com.redhat.quarkus.lsp4e/src/com/redhat/quarkus/lsp4e/QuarkusLanguageClient.java#L21

**Comment by ArneDeutsch** [comment]
I try to get my language server running in the same process es eclipse and face the same issue. Have you succeeded to get this running or any more information?

**Comment by angelozerr** [comment]
To be honest with you I have not a solution today since we change the strategy to start Quarkus LS.
