### ISSUE TITLE
Interaction with JDT (LS) ?

### ISSUE THREAD

**Issue by mickaelistria** [angelozerr/quarkus-lsp4e#2]
How is this Quarkus LS supposed to interact with JDT/JDT-LS inside Eclipse IDE?
I think JDT-LS enforces some specific project layout/open state under the hood, that's not visible in other IDEs, but that would become visible (and maybe annoying for end-users) in the Eclipse IDE.
Can you please explain how those are integrating, and clarifies whether my concerns about Quarkus LS altering the user workspace state would actually happen or not?

**Comment by angelozerr** [comment]
> How is this Quarkus LS supposed to interact with JDT/JDT-LS inside Eclipse IDE?

We have discussed with @fbricon about this topic, and the idea is not to use JDL LS inside Eclipse IDE.

There are 2 solutions to do that:

 * Spring Tools solution : they re-implement the JDL LS command handler plugin inside Eclipse IDE. It means that their language server communicate with JDT by serialising JSON stream (request/response from the language server / command handler)
 * Quarkus LS : we consume directly the JDT plugin inside our language server. It avoid this step of serailizing/deserialising JSON stream. But it requires that the language server must be started in the same JVM than Eclipse IDE.

**Comment by mickaelistria** [comment]
I think both are expensive Eclipse-specific development that would be quite expensive and not reusable.
I would suggest as 1st iteration simply binding the LS (which may require JDT-LS) as a separate process, exactly like it's done in VSCode and just see it working. Then it will be easier to figure out what track is better to pursue, if any.

**Comment by angelozerr** [comment]
It means that you will have double parsing of Java file, and double start of a lot of plugins. 

@fbricon @jeffmaury what do you think about that?

**Comment by mickaelistria** [comment]
> It means that you will have double parsing of Java file, and double start of a lot of plugins.

To me, there are much worse issue, like spending huge effort for an IDE-specific integration when the whole domain is about making language smartness IDE-agnostic.
Keeping language server a black-box is what makes the value; when starting to open that box, then it's immediately worth wondering why even using a language server at all instead of other ways of doing specific IDE integrations.

**Comment by fbricon** [comment]
> It means that you will have double parsing of Java file, and double start of a lot of plugins.
> 
> @fbricon @jeffmaury what do you think about that?

This is a total non-starter. We have a cheap way of integrating quarkus-ls with jdt, the current implementation in this repo, that doesn't come with all those drawbacks, so let's do that.

**Comment by mickaelistria** [comment]
> We have a cheap way of integrating quarkus-ls with jdt, the current implementation in this repo, that doesn't come with all those drawbacks, so let's do that.

I think your answer lacks pragmatism and encouraging IDE-specific integrations doesn't seem aligned with the goals of our teams.
Is it really cheap? Would there be any value or experimental work reusable outside of this specific EclipseIDE+QuarkusLS integration? Are we optimistic about the ROI on this one?
End-users don't really care about duplicating computing resources as long as it makes them more productive. Also, Red-Hat-business-wise, I don't think optimizing the consumption of resources on end-users workstation is high priority (compared to optimizing them in the cloud).
We IMO really need a 1st iteration working with the LS as a black box before deciding whether to invest more.
cc @gorkem , please have a look at this debate.

**Comment by maxandersen** [comment]
> Also, Red-Hat-business-wise, I don't think optimizing the consumption of resources on end-users workstation is high priority (compared to optimizing them in the cloud)

The proposed solution most likely would highly benefit consumption of resources in the cloud too. 
And please - lets not make it a goal that tools need clusters to run. Goal is to make something users can and will use.

@mickaelistria the challenge here is really that only a certain class of languages and extensions can live in full isolation. Thus for example in "pure" LSP's IDE you see things like quarkus tooling call out to jdt.ls to get the java info it needs rather than reparse/reimplement it again.

Rather than dismissing the current proposal could you come with a proposal to solve it in Eclipse IDE land ? one we could work towards while at the same time have this current minimal proposal rolled out to gain experience from ?

**Comment by mickaelistria** [comment]
I think the 2 goals:
1. Get Quarkus support in Eclipse IDE, and
2. Improve LSs interoperability

are not so related and are orthogonal: we can make progress on any of both topics without necessarily making it a dependency for progress on the other topic; while there is indeed a point of interest at the intersection that'd be nice to spot.
Trying to force a strong relationship between both would at least delay the "time to market" of Quarkus support in Eclipse IDE. If it's fine for its maintainers, good for them.

Also, I think the problem of interoperable Language Services, while a solution would be welcome, isn't a blocker in the domain. Things like Angular or HTML assistance support in JS files with some internal magic (maybe duplication, maybe factorization...) have worked fine so far without being seen as a challenge.
Tools like VSCode for example keep multiple processes for the same files, duplicate a lot of logic, classes, modules... in different services and so far, it's not an issue. Why would it be a big one for Eclipse IDE?

We could imagine an initiative to think about how JDT-LS extensions can integrate better in the Eclipse IDE, but to me, it seems very far from being a priority as there are already decent approaches that do work (starting the LS as a separate process, duplicating some state on client and server) and provide the same value and I don't see any valid reason why making it a requirement for a 1st milestone of Quarkus support in Eclipse IDE.

**Comment by maxandersen** [comment]
Angular and html tooling require very little semantic language understanding and the tooling around it is generally much lighter in comparison to Java requiring jdt, m2e, buildship and more loaded to have its "complete" model. 

Also adding something like quarkus tools is to compare to have specific framework built on top of anguluar supported - and I think you would then bump into similar issues.

But sounds like we are agreeing that LSP interoperability is not great today and if its simply for quarkus tooling to maintain and hook  into JDT to solve its fairly simple usecase then that is fine.

**Comment by angelozerr** [comment]
Sorry to have creating this kind of discussion. I found a solution to start Quarkus LS with standard mean (with LSP4E process) and I can consume on client side JDT without using JDL LS.

**Comment by maxandersen** [comment]
cool - got a pointer to how that works ? would love to see ;)

**Comment by angelozerr** [comment]
> cool - got a pointer to how that works ? would love to see ;)

As soon as I will time, I will try to draw a schema to explain how it works. I would like to have too a schema for vscode-java with JDT LS.
